stages:
  preprocess:
    cmd: poetry run python -m ${moduleName}.data.preprocess
    deps:
      - src/${moduleName}/data/preprocess.py
      # data/raw/ is not listed as a dep because it must be added manually
      # the first time. After adding raw data, you can uncomment the line below
      # to let DVC track changes to it:
      # - data/raw/
    outs:
      - data/processed/
  train:
    cmd: poetry run python -m ${moduleName}.train
    deps:
      - src/${moduleName}/train.py
      - src/${moduleName}/model/model.py
      - src/${moduleName}/data/datamodule.py
      - data/processed/
      - params.yaml
    params:
      - training
    outs:
      - models/model.ckpt:
          cache: false
  evaluate:
    cmd: poetry run python -m ${moduleName}.eval
    deps:
      - src/${moduleName}/eval.py
      - src/${moduleName}/model/model.py
      - models/model.ckpt
      - data/processed/
      - params.yaml
    params:
      - evaluation
    outs:
      - evaluation_results.json
