stages:
  preprocess:
    cmd: python -m ${moduleName}.data.preprocess
    deps:
      - ${moduleName}/data/preprocess.py
      - data/raw/
    outs:
      - data/processed/
  train:
    cmd: python -m ${moduleName}.train
    deps:
      - ${moduleName}/train.py
      - ${moduleName}/model/model.py
      - ${moduleName}/data/datamodule.py
      - data/processed/
      - params.yaml
    params:
      - training
    outs:
      - models/model.ckpt:
          cache: false
  evaluate:
    cmd: python -m ${moduleName}.eval
    deps:
      - ${moduleName}/eval.py
      - ${moduleName}/model/model.py
      - models/model.ckpt
      - data/processed/
      - params.yaml
    params:
      - evaluation
    outs:
      - evaluation_results.json