data:
  image_size: (28, 28)
  num_classes: 10
  num_channels: 1
  
training:
  batch_size: 32
  lr: 0.001
  max_epochs: 10
  num_workers: 4
evaluation:
  batch_size: 32
  num_workers: 4

release:
  # Model release configuration
  # Version will be auto-detected from git tags, or use 'dev-{commit_hash}'
  # S3 bucket and prefix can be overridden via environment variables:
  # MODEL_RELEASE_S3_BUCKET, MODEL_RELEASE_S3_PREFIX