data:
  image_size: [224, 224]
  num_classes: 10
  num_channels: 3

training:
  batch_size: 32
  lr: 0.001
  max_epochs: 10
  num_workers: 4
  # Tip: If you hit GPU OOM errors, reduce batch_size or image_size first.
  # Large models (e.g. detection, segmentation) may need batch_size: 2-4.

evaluation:
  batch_size: 32
  num_workers: 4

release:
  # Model release configuration
  # Version will be auto-detected from git tags, or use 'dev-{commit_hash}'
  # S3 bucket and prefix can be overridden via environment variables:
  # MODEL_RELEASE_S3_BUCKET, MODEL_RELEASE_S3_PREFIX
